### ISSUE TITLE
python读取zyenpheng.dict.yaml出现unacceptable characterReaderError: unacceptable character #x20dff: special characters are not allowed

### ISSUE THREAD

**Issue by laubonghaudoi** [rime/rime-middle-chinese#1]
我想用python自制一个发音字典，通过读取.dict.yaml中的dict，输入汉字输出拼音，一开始的代码如下：
```
import yaml
f = open('zyenpheng.dict.yaml')
x = yaml.load(f)
```
但是出现以下错误：
`ReaderError: unacceptable character #x20dff: special characters are not allowed`
.yaml文件不支持utf-32编码，zyenpheng.dict.yaml用的是什么编码？是否有办法忽略这些生僻字？或者其他解决办法？

**Comment by osfans** [comment]
---和...之間的才算是yaml的內容了。

建議直接解析...後面的內容。

```yaml
# Author:
#  - polyhedron <biopolyhedron@gmail.com>
#

---
name: zyenpheng
version: "2015.09.01"
sort: by_weight
use_preset_vocabulary: true
...

𠂇	cax	
```
